### PR TITLE
Remove DBusActivatable

### PR DESCRIPTION
**Pull request by mcatanzaro**
https://phabricator.endlessm.com/T10840
https://phabricator.endlessm.com/T12405

### CODE REVIEW

**Comment by mcatanzaro** [comment]
@joaquimrocha, please review.

**Comment by joaquimrocha** [comment]
Could you elaborate? This file hasn't been touched from upstream, should this change go there?

**Comment by mcatanzaro** [comment]
No, this change should not go upstream. eos-shell can't handle D-Bus activation properly, see T10840.

**Comment by joaquimrocha** [comment]
Ah, ok. Thanks.

**Comment by mcatanzaro** [comment]
It's to get the speedwagon when launching the app (note it's currently missing).

**Pull request merged**
