### PR TITLE
Improve UX for removing apps

### PR DESCRIPTION
**Pull request by ptomato**
https://phabricator.endlessm.com/T28699

### CODE REVIEW

**Comment by ptomato** [comment]
Upstream merge request: https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/367

**Comment by pwithnall** [comment]
I [left a review upstream](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/367#note_655187).

**Comment by ptomato** [comment]
I removed the commit that's still under discussion in https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/367 (since it will probably have to be rewritten anyway) and just left the uncontroversial minor fixes here.

There's another upstream merge request that now has the same content as this one: https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/386

**Comment by pwithnall** [comment]
[Merged upstream](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/386#note_665053), so let’s merge it downstream too

**Pull request merged**
