### PR TITLE
T32854 Rebase on 41.3

### PR DESCRIPTION
**Pull request by pwithnall**
Rebase gnome-software on upstream 41.3. This drops a lot of commits (basically all the UI changes and USB support), and a number of the remaining ones are due for upstreaming if I find some time next week.

Packaging changes are in #581.

https://phabricator.endlessm.com/T32854

### CODE REVIEW

**Comment by pwithnall** [comment]
Here is the commit-by-commit breakdown, which should be more useful for review than looking at the diff or commit list:

`git ria upstream/gnome-41` (`24b9a0ccd`)

 * **drop** `de5861309 Release version 3.38.0` — already upstream
 * **drop** `e8bc17322 Revert "Remove the now-unused code that supported the colorful category buttons"` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `c69b7eefe core: Add USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `5ed1aa045 flatpak: Select USB category when loading a folder that has a removable remote` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `db30a2ed7 flatpak: Allow offline installation of apps that have the USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `a074af211 Set gnome-software as default handler for x-content/ostree-repository` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `0eb36640a flatpak: Emit updates-changed when a USB remote is loaded` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `e121e20d1 lib: Make gs_app_{get,set}_priority() public` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `be41927f7 flatpak: Add collection ID support to GsFlatpakApp` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `de4585785 flatpak: Add apps to the USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `56286e925 flatpak: Reload plugin when a removable remote is unmounted` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `5da768c79 gs-plugin-job: Add copy-dest property` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `d2f67e94e gs-plugin-loader: Add vfuncs for copying an app` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `3c175c4bc gs-plugin-loader: Add monitoring of mounted USB drives` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `6e51b04cd gs-plugin: Add new GS_PLUGIN_STATUS_COPYING status` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `e19cbacd5 flatpak: Set flatpak::ExtraData for extra-data apps` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `698a7c4aa flatpak: implement copying an app to removable media` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `00871be2e gs-page: Add gs_page_copy_app() to support copying apps to USB drives` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `8dee4a5cf details page: restructure code to handle progress indicators` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `b4e204348 gs-details-page: Add a ‘Copy to USB’ button for copying apps` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `8a49fdfc0 Display the USB category even if the inserted disk has no apps` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `a3e27d65c Show empty state message for USB category for appless disks` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `97690e000 lib: Ignore USB sticks if they are read-only` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `751a75eee gs-plugin-loader: Add vfuncs for copying the OS` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `6900eb344 gs-page: Add gs_page_copy_os() to support copying the OS to USB drives` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `94cf578e4 Add 'copy OS to USB' button to USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `6009917e6 src: Expose origin hostname in app details for blocklisting` — keep for now; FIXME: move blocklisting to a static appstream file later; minor rebase conflicts
 * pick `f5a8955d6 eos: Add eos-blocklist plugin` — keep for now; FIXME: move blocklisting to a static appstream file later
 * pick `b55dbb8fc gs-prefs-dialog: Hide automatic updates setting when using Mogwai` — keep for now; FIXME: upstream later; significant rebase conflicts, so reworked significantly
 * pick `2ffe0d6e1 Add the top bar about auto updates to the Updates page` — keep for now; FIXME: upstream later; significant rebase conflicts, so reworked significantly; I think this is the last commit which requires us to keep downstream translations, so is a priority to upstream
 * **drop** `9e5032cd0 eos: Hide the recent box` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `dac1c7a40 Add EOS desktop plugin` — not needed itself since the app grid changes in gnome-shell, but needed as the basis for a number of subsequent changes, such as support for launching Chrome
 * pick `45abe66b3 eos: Disallow uninstallation of core applications` — keep for now; FIXME: upstream later
 * **drop** `520c70eb9 Add GsSideFilterRow widget` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `aa1981471 Add a side filter list to the shell` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `c9b6d0f2f Set the side filter categories from the overview` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `e8a1d834a Keep the top tabs visible when in the category page` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `f97b6f6f8 eos: Set the image tile CSS from a special metadata key` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `9eb2c565f Use a GtkFlowBox for displaying the popular apps in the overview` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `3e6315786 Adapt the app's grid in the overall/category views to the UI specs` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `c24a98442 app: Add detailed signal for when metadata is updated on an app` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `4e203c1e6 eos: Download backgrounds for app thumbnails and cache them.` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `68c97dd35 Sort popular apps alphabetically based on GSettings` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `334f19078 Remove DBusActivatable` — subsequently reverted
 * **drop** `7dc0534e5 eos: Adapt existing categories to fit Endless users' needs` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `b134a8fa5 updates: launch app page when clicking on update row` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `1cd79e615 Change user-facing name from Software to App Center` — keep for now; FIXME: do user research and potentially drop/change later
 * **drop** `009e73a17 ui: Rename ‘Remove’ to ‘Uninstall’` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `6f529d811 gs-details-page: Rename shortcut buttons to ‘Add to/Remove from Desktop’` — subsequently reverted
 * **drop** `8896cf09f Emphasize the "Add to Desktop" button` — subsequently reverted
 * **drop** `40e214f2a eos: Support desktop icons for apps that use helper desktop files` — not needed since app grid changes in gnome-shell
 * **drop** `2a50264fd Show the search button in the category and installed views` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `3c75497a6 Disable the featured banner` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `2fec23dde Hide the "Editor's Picks" label in the featured page` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `e6f424dc0 eos: Fix launching Google Chrome` — keep until Chrome can be run using `flatpak run` directly
 * **drop** `7ae4f216e feed: Add an EOS Discovery Feed Content Provider` — subsequently reverted
 * **drop** `d3e81dbda eos: Override certain icons when adding to desktop` — subsequently reverted
 * **drop** `382b86eda Add the new GsBackgroundTile` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `e61d8eda8 Use the GsBackgroundTile in the overview and category pages` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `fe06a97ef updates: Set the refresh button insensitive when apps are updating` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `34a30faa0 Use the speedwagon when opening GNOME Software` — subsequently reverted
 * **drop** `e557a430c Make the Add-to-desktop button the first button in the details page` — subsequently reverted
 * **drop** `d8e519801 Use GenericName in the desktop file to provide an alternative name` — not needed since app grid changes in gnome-shell
 * pick `2ae766ca4 Limit the number of certain ops in parallel to 1` — keep until the threading rework is complete in gnome-software 42
 * pick `6a1b30640 build: Override meson's default options` — keep for now; FIXME: move options to Jenkins job builder template later; minor rebase conflicts
 * pick `0315bec57 Never show the first run dialog` — keep for now; FIXME: [upstream later](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1399); minor rebase conflicts
 * **drop** `1f6c8ee89 src: Re-style OS upgrade background and buttons` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `44cd038cc Remove the big shopping bag icon from the loading page` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `1d783dfb2 flatpak: Set the apps' update priority` — keep for now; FIXME: [upstream a reduced default policy later](https://phabricator.endlessm.com/T32778#917765); minor rebase conflicts
 * **drop** `fd2272164 ui: Rename ‘Install’ to ‘Download’` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `0eec53b09 gs-details-page: Label button as ‘Install’ not ‘Download’ for USB apps` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `5337d9bcb Do not invalidate OS upgrades in the Updates page` — keep for now; FIXME: upstream later; minor rebase conflicts
 * **drop** `2df1e4d39 Display the USB icon in the background tile` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `40286981c eos: Make getting an app's desktop ID more robust` — squashed into earlier commit “eos: Fix launching Google Chrome”
 * **drop** `7167c858f flatpak: Don't disable the plugin if an installation setup succeeds` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/237)
 * **drop** `dd1d821c9 flatpak: Refactor the plugin's setup method` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/237)
 * pick `8293818eb Add an "interactive" refine flag` — keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `ca3affc89 Use the interactive flag in the details page's jobs` — keep for now; FIXME: upstream later; minor rebase conflicts
 * **drop** `c5ba73a97 Lower the minimum number of popular apps required to be shown` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `359ae2b92 Save/load install queue using unique IDs` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `867669b20 Fix showing the apps queued for installation in the installed page` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `5894d6182 Try to install the apps that are queued after adding them` — install queue support; keep for now; FIXME: upstream later
 * pick `32d72d262 Allow to cancel installation of apps that were queued for install` — install queue support; keep for now; FIXME: upstream later
 * pick `d62c547c5 Use a GsAppList for the pending apps` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `2397a36cc Fix order of saving apps that are queued install` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `c8e892a8a Fix updating the installation queue on disk` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `8c754171e Always add apps that are to be installed to the install queue` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `9a2a972ef Fix how pending apps are installed from the installed page` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * **drop** `553f103dc Display ongoing app-update at top of the list` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * pick `65e4a4f6a Allow to cancel pending installations that are queued` — install queue support; keep for now; FIXME: upstream later
 * pick `25fded336 Simplify how apps queued-for-install are cancelled` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * **drop** `5c69f1926 flatpak: Return no-network error when failing to fetch remote metadata` — [independently fixed upstream](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/0fbeaddc82)
 * **drop** `68fd07d25 eos: add support for copying OS` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `183b09c5f eos: fix asking shell to add/remove "[Invalid UTF-8]"` — subsequently reverted
 * **drop** `246fc4cb8 eos: Check for OS updates on USB insertion` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `544930ef9 Only show "Copy to OS to USB" button if it might work` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `86818f966 flatpak: Ignore FLATPAK_ERROR_ALREADY_INSTALLED when installing apps` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/247)
 * **drop** `74ddec86c eos: Add EknServicesMultiplexer as a related app for EKN apps` — [no longer needed](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `f5ba21000 gs-appstream: Add support for Endless::HasDiscoveryFeedContent searches` — subsequently reverted
 * **drop** `0883160c3 add Learn to Code category` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `131a710ce Select category correctly when "Back" is clicked` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `722ae9559 appdata: remove release notes` — keep for now; FIXME: drop if we are able to drop doing downstream translations; minor rebase conflicts
 * **drop** `753a4a435 details-page: Place "Uninstall" button below app screenshots` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `ac1899cb1 Replace desktop icon with Endless asset` — subsequently reverted
 * **drop** `b31b8e215 gs-app-tile: Refresh the app tile when the app’s action changes` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `9bda39322 gs-app-tile: Refresh the app tile when the app’s metadata changes` — [dropping UI customisations](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `c7a3759b0 eos-updater: Call the correct gs_plugin_refresh() implementation` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `bf1400187 flatpak: Properly populate USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `326be3d76 flatpak: Introduce success/failure heuristics for app install and autoupdates` — needs to be kept until [landed in flatpak](https://github.com/flatpak/flatpak/pull/3013), unless we rely on carrying the flatpak changes downstream; minor rebase conflicts
 * **drop** `9cddd8f33 Reload USB category on USB insertion` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `83389ff7f flatpak: Only show apps in the USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `0d28a1940 updates monitor: Don't skip automatic updates that require new permissions` — keep until there has been [upstream progress](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/943) on presenting permissions updates to users
 * pick `498ae2e35 appstream: Override <id> with <launchable type="desktop-id"> while parsing appdata files` — keep for now; FIXME: upstream later
 * pick `447797b36 HACK: Disable timeout for plugin job operations` — keep for now; FIXME: upstream later; [commit it is supposed to fix](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/d88d63b253) has already been upstreamed
 * **drop** `092f4cca1 gs-plugin-loader: Show spinner only on app being copied to USB` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * pick `a3ee8a6af Integrate Transifex translation infrastructure` — necessary translation infrastructure
 * pick `24b7af645 eos: Add parental controls metrics on update poll` — keep for now; FIXME: rework and move out to a separate component later
 * pick `b4a180a78 Add translation support for several new languages` — necessary translation infrastructure; minor rebase conflicts
 * **drop** `ebd68aa41 flatpak: Block on download scheduler for updates` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/cf9b2dfa45)
 * **drop** `31746b679 gs-metered: Remove Mogwai schedule entries when downloads are complete` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/3e635df34da24704b8293fc12cc3bb0a1a0c12e7)
 * pick `50c304c6f lib: Skip mogwai checks in unit tests` — keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `391013da1 gs-app: Allow change from AVAILABLE_LOCAL to QUEUED_FOR_INSTALL` — keep for now; FIXME: upstream later; minor rebase conflicts
 * **drop** `59d81621f tests: Skip flatpak parental controls checks` — subsequently reverted
 * pick `68d989e78 gs-plugin-loader: Don't erroneously set apps to AVAILABLE` — install queue support; keep for now; FIXME: upstream later; minor rebase conflicts
 * pick `0d96f4030 flatpak: Skip self tests on arm` — keep for now; FIXME: should be upstreamed if we don’t work on making the tests [architecture agnostic](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1047)
 * **drop** `a11558d90 flatpak: Fix offline installation` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/505)
 * **drop** `aea823302 Revert "Use the speedwagon when opening GNOME Software"` — revert of earlier commit
 * **drop** `4842711fd Revert "Remove DBusActivatable"` — revert of earlier commit
 * **drop** `89ce60aac Revert "gs-appstream: Add support for Endless::HasDiscoveryFeedContent searches"` — revert of earlier commit
 * **drop** `52bf1fe5f Revert "feed: Add an EOS Discovery Feed Content Provider"` — revert of earlier commit
 * **drop** `1a36e5001 Revert "eos: fix asking shell to add/remove "[Invalid UTF-8]""` — revert of earlier commit
 * **drop** `4d7f6b06b Revert "Make the Add-to-desktop button the first button in the details page"` — revert of earlier commit
 * **drop** `9aa6d1cb1 Revert "eos: Override certain icons when adding to desktop"` — revert of earlier commit
 * **drop** `b2a1c664a Revert "Emphasize the "Add to Desktop" button"` — revert of earlier commit
 * **drop** `4b4cb8731 Revert "gs-details-page: Rename shortcut buttons to ‘Add to/Remove from Desktop’"` — revert of earlier commit
 * pick `eb9e88a96 eos: Revert desktop shortcut support from EOS plugin` — squashed into earlier commit “Add EOS desktop plugin”
 * pick `5d9405a5e eos: Remove Totem from blocklist` — squashed into earlier commit “eos: Add eos-blocklist plugin”
 * **drop** `c61a94964 New translations from Transifex` — translations
 * **drop** `f12450f42 New translations from Transifex` — translations
 * **drop** `7315f685f flatpak: Fix adding apps to USB category` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `013686198 flatpak: Use new flatpak API to automatically remove EOL runtimes` — [already upstreamed](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/b01c36b750)
 * pick `1651427d7 eos: Remove rhythmbox from blocklist` — squashed into earlier commit “eos: Add eos-blocklist plugin”
 * pick `4a7674f18 eos: Remove eos-link-* special handling from blocklist` — squashed into earlier commit “eos: Add eos-blocklist plugin”
 * **drop** `2228f6007 eos: Correctly set interactive status for USB operations` — [dropping USB support](https://phabricator.endlessm.com/T32778#917765)
 * **drop** `a6f9fcafb Revert "Replace desktop icon with Endless asset"` — revert of earlier commit
 * pick `f5e6bc090 eos: Stop marking all non-flatpak apps as installed and compulsory` — squashed into earlier commit “eos: Disallow uninstallation of core applications”
 * **drop** `02e008781 flatpak: Fix assertation in new libflatpak version` — only [present upstream on 3.38 branch](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/c0a287cd7620274010fda1e9b998bb41ec610bb5); seems to not be needed on `main`
 * **drop** `ec18abb2f New translations from Transifex` — translations
 * **drop** `8f5938a77 New translations from Transifex` — translations
 * **drop** `ad1c495a8 New translations from Transifex` — translations
 * **drop** `254abc8fa [DROP-ME] tests: Temporarily disable failing tests` — subsequently reverted
 * **drop** `8abbfa8d5 Revert "tests: Skip flatpak parental controls checks"` — revert of earlier commit
 * pick `da0d339d5 tests: Skip parental controls in the upstream way` — keep for now; FIXME: upstream later
 * **drop** `5d9abb74d Revert "[DROP-ME] tests: Temporarily disable failing tests"` — revert of earlier commit
 * pick `4ca1e6126 eos-blocklist: Remove GNOME Calculator from blocklist` — squashed into earlier commit “eos: Add eos-blocklist plugin”
 * pick `2e58ee483 eos-blocklist: Remove Gedit from blocklist` — squashed into earlier commit “eos: Add eos-blocklist plugin”

`# Rebase 24b9a0ccd..a73f24a50 onto 24b9a0ccd (156 commands)`

**Comment by pwithnall** [comment]
bot, rebuild this please

**Comment by pwithnall** [comment]
bot, retest this please

**Review by GeorgesStavracas — APPROVED** [review]
I don't have any comments in particular. This was quite a large rebase. I'm happy to see so many patches being dropped.

**Pull request merged**
