### PR TITLE
T29985 Fix progress handling of skipped apps

### PR DESCRIPTION
**Pull request by mwleeds**
https://phabricator.endlessm.com/T29985

### CODE REVIEW

**Comment by mwleeds** [comment]
This has already been through one round of review:

- https://github.com/endlessm/gnome-software/commit/5251ee94f4582569b1e94a501c2bdf84fe5884ed#r40448829
- https://github.com/endlessm/gnome-software/commit/334f2f230558b29f8fde19f593cb347f2fa1fca6#r40448323

**Comment by mwleeds** [comment]
When I went to make an upstream MR for this, I found that [this related MR](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/373) was never merged. The patches here do not directly depend on the ones there but one of the commits here reference those changes in a comment in `_transaction_operation_done()`. So I suppose the right thing to do is resurrect that MR, clean it up, add unit tests, and add this stuff on top of it.

**Comment by pwithnall** [comment]
I left a review upstream: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/490/commits

**Comment by mwleeds** [comment]
This branch is based on #548 to reduce merge conflicts, and also includes two upstream commits to reduce confilcts:
```
7d54e2835 tests: Avoid using a hard-coded directory for temporary test data
958c9049d tests: Remove an unused environment variable
```

There's also a downstream commit to change the Flatpak version checks.

**Comment by mwleeds** [comment]
This is rebased on master after #548 landed

**Pull request merged**
